"""
Django settings for pysite project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h)*j3^xvve)4+l7&s-=3e-o$$@f-mr@b+*j!_%l*tsp(5i_w_w"

# True if data migrations should run
DATA_MIGRATIONS = True

UNIT_TEST = False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'website'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, 'website/views'),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'stablediffxl_db',
        'USER': 'stablediffxl_admin',
        'PASSWORD': 'pass',
        'HOST': 'localhost',
        'PORT': '5432',
        'TEST': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'stablediffxl_db_dev',
            'USER': 'stablediffxl_admin',
            'PASSWORD': 'pass',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = "website/static"
STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, 'website/static')
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
    },
}

# Twilio
TWILIO_SMS = {
    'ACCOUNT_SID': 'xxx',
    'AUTH_TOKEN': 'xxx',
    'PHONE_NUMBER': '+1xxxxxxxxxx',
}

# Send grid
SEND_GRID = {
        'API_KEY': 'SG.xxx',
        'FROM_EMAIL': 'xxxxx@email.com',
}

S3_ACCESS = {
    'MODE': 'PROD',
    'BUCKET': "bucket",
    'REGION': 's3.us-west',
    'HOST': 'amazonaws.com',

    'EXTRA_ARGS': 'public-read',
    #'ACCESS_KEY': '',
    #'SECRET_KEY': '',
}

FCM_API_KEY = "AAAA"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

### FastAPI and Pytorch settings

FAST_API = {
    'allow_origins':        ['localhost:8000'],
    'allow_credentials':    True,
    'allow_methods':        ["*"],
    'allow_headers':        ["*"],
}

OPENAI_API_KEY ='xxx'

MODLE_NAME = 'gpt-3.5-turbo'

PAYLOAD_PATH = '/tmp/ink2ai'

DISCORD = {
    "LINK": "https://discord.gg/xxxxxx",
    "BOT_TOKEN": "xxxxxx",
    "CHANNEL_ID": "xxxxxx",
    "BOT_ID": "xxxxxx",
}
